//exception is an abnormal code

// exception handling

//try, catch finally throw
var num1=10;
var num2=0;
try{
if(num==0) throw "division by zero"
var res = num1/num2;
console.log("res =" +res)
}

catch{
    console.log(err)
}
// try{
    //doubtfull code
//}

//catch{
    // handling code
//}